services:
  backend:
    image: ${BACKEND_IMAGE}:${TAG}
    container_name: member-engagement-backend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CALENDAR_ID=${GOOGLE_CALENDAR_ID}
      # CORS_ORIGIN will be set in the prod override file
    networks:
      - app-network

  frontend:
    image: ${FRONTEND_IMAGE}:${TAG}
    container_name: member-engagement-frontend
    restart: unless-stopped
    expose:
      - "5174" # Assuming the frontend runs on this port inside the container
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: member-engagement-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/deploy/certbot/conf:/etc/letsencrypt:ro
      - /home/deploy/certbot/www:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
