name: Build and Deploy

on:
  push:
    branches: [main, live]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FRONTEND: ${{ github.repository }}-frontend
  IMAGE_NAME_BACKEND: ${{ github.repository }}-backend

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=live,enable=${{ github.ref == 'refs/heads/live' }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/frontend
          file: ./packages/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=live,enable=${{ github.ref == 'refs/heads/live' }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/backend
          file: ./packages/backend/Dockerfile
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

  deploy:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/live' && github.event_name == 'push'

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          envs: GITHUB_TOKEN,GITHUB_ACTOR,GITHUB_REPOSITORY
          script: |
            echo "Starting deployment..."
            cd /opt/member-engagement-app || { echo "Application directory not found"; exit 1; }

            echo "Logging into GitHub Container Registry..."
            echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin

            echo "Setting image tag to: live"
            export IMAGE_TAG=live

            echo "Stopping existing containers..."
            docker-compose -f docker-compose.prod.yml down

            echo "Removing old images to force fresh pull..."
            docker image rm "ghcr.io/$GITHUB_REPOSITORY-frontend:live" 2>/dev/null || true
            docker image rm "ghcr.io/$GITHUB_REPOSITORY-backend:live" 2>/dev/null || true
            docker image rm "ghcr.io/$GITHUB_REPOSITORY-frontend:latest" 2>/dev/null || true
            docker image rm "ghcr.io/$GITHUB_REPOSITORY-backend:latest" 2>/dev/null || true

            echo "Pulling latest Docker images with tag: $IMAGE_TAG..."
            IMAGE_TAG=live docker-compose -f docker-compose.prod.yml pull

            echo "Starting services with fresh images..."
            IMAGE_TAG=live docker-compose -f docker-compose.prod.yml up -d

            echo "Waiting for services to be ready..."
            sleep 15

            echo "Verifying deployment..."
            IMAGE_TAG=live docker-compose -f docker-compose.prod.yml ps

            echo "Cleaning up unused Docker resources..."
            docker system prune -f

            echo "Logging out of GitHub Container Registry..."
            docker logout ghcr.io

            echo "Deployment completed successfully!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
